### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by cdolek** [meteor-useraccounts/core#679] opened 2016-05-10 11:41 UTC
http://useraccounts-bootstrap.meteor.com/
http://useraccounts-foundation.meteor.com/
http://useraccounts-ionic.meteor.com/
http://useraccounts-materialize.meteor.com/
http://useraccounts-polymer.meteor.com/
http://useraccounts-ratchet.meteor.com/
http://useraccounts-semantic-ui.meteor.com/

**Comment by fafournier** [comment] 2016-05-11 17:23
duplicate of #660

**Closed** 2016-05-18 22:41 UTC
