### ISSUE TITLE
"Must be logged in" error displayed after sign out on public route

### ISSUE THREAD

**Issue by maxxx333** [meteor-useraccounts/core#321] opened 2015-03-18 22:34 UTC
router.js:
```javascript
Router.plugin('ensureSignedIn', {
    except: ['atForgotPwd', 'atSignIn', 'atSignUp', 'signOut', 'root']
});

Router.route('/dashboard', {
    name: 'dashboard',
    layoutTemplate: 'masterLayout',
    yieldRegions: {
        'navbar': {to: 'navbar'}
    },
    action: function () {
        this.render();
    }
});

Router.route('/sign-out', {
    name: 'signOut',
    onBeforeAction: function () {
        Meteor.logout(function () {
            Router.go('root');
        });
        this.next();
    }
});
```

I think problem is:

1. Go to /dashboard
2. Iron route dispatch started
3. Computation created - https://github.com/iron-meteor/iron-router/blob/devel/lib/route_controller_client.js#L86
4. OnRun called - https://github.com/meteor-useraccounts/core/blob/master/lib/client.js#L156
5. Meteor.loggingIn() reactive
6. Computation created on third step rerun after invalidate loggingIn on submit sign in form - https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L172
7. onBeforeAction called - https://github.com/meteor-useraccounts/core/blob/master/lib/client.js#L163
8. "Must be logged in" error added - https://github.com/meteor-useraccounts/core/blob/master/lib/client.js#L120
9. dashboard rendered
10. "Must be logged in" error not cleared from AccountsTemplates
11. Click sign out
12. Redirected to 'root'
13. Form with "Must be logged in" error appeared
14. If reload then error disappeared

**Comment by splendido** [comment] 2015-03-26 09:06
Sorry for the late reply!

I'll try to have a look at this asap... :(

**Comment by splendido** [comment] 2015-04-18 10:46
When `v1.9.0` will be out let mw know if this is solved also from your side.

Thanks for reporting,
Luca

**Comment by chiester** [comment] 2015-04-20 17:24
I just updated to 1.9.1 and I'm still seeing this behavior.

**Comment by chiester** [comment] 2015-04-20 17:27
I had this same issue and indeed it appears to be fixed now. (I had previously stated I thought it wasn't fixed, but I just needed to clear cache).

**Comment by chiester** [comment] 2015-04-20 17:54
I have 1.9.1 and I'm still seeing this same problem.

**Comment by splendido** [comment] 2015-04-20 20:25
Do anyone have a public repo reproducing this issue?

**Comment by chiester** [comment] 2015-04-21 06:01
Here's the repo where I reproduced it, https://github.com/chiester/useraccounts-bug/tree/master/bootstrap

* Pull down and run
* Register a user
* Sign In
* It routes you to the private page
* Sign Out
* It routes you to home, but shows the "Must be logged in" message
* Refresh page and "Must be logged in" message disappears

**Comment by chiester** [comment] 2015-04-21 15:10
I worked around this. Rather than putting my "/" route in router.js, since I wanted my root to also be the sign in screen, I put it in at_config.js, like 
```
AccountsTemplates.configureRoute('signIn', {
	name: 'signIn',
	path: '/',
	template: 'home',
	layoutTemplate: 'loginLayout',
	redirect: function() {
		var user = Meteor.user();
		if (user) {
			Router.go('/dashboard');
		} else {
			this.next();
		}
	}
});
```

**Comment by splendido** [comment] 2015-04-21 16:05
I tested it and I can confirm myself the problem.
I'll try to have a look at it...

**Closed** 2015-04-21 19:45 UTC

**Comment by splendido** [comment] 2015-04-21 19:48
finally got it! ;-)
...the thing is that when you logout while you're on a *protected* route there's one more reactive computation of `onBeforeAction` hooks before you actually leave the page and `ensureSignedIn` set the error again :(

Solved by adding an `onStop` hook to clear the error every time you leave a *protected* route ;-)


thanks for reporting!

**Comment by wlundgren** [comment] 2015-05-19 10:51
I dealt with this configuring hook onLogoutHook in AccountsTemplates.configure with a Route to the homepage (not private). And it works like a charm. You may try it and see if it works for you.

**Comment by splendido** [comment] 2015-05-19 11:17
could you please paste a bit of code @wlundgren?

**Comment by wlundgren** [comment] 2015-05-19 13:46
Sure. 
@chiester maybe this is not exactly your case but it also happened to me that as soon as a user logged out they saw a Sign In page with a message like "you need to be logged in to see this page".

I have the ensureSignedIn plugin in a few routes like this:
// make this pages available only to logged in users
Router.plugin('ensureSignedIn', {
    only: ['private']
});

So what I do is to redirect the users to a public page after logging out like this:
AccountsTemplates.configure({
...
    // Hooks
    onLogoutHook: function() {
      console.log("onLogoutHook");
      Router.go("/");  // here I redirect to my homepage
    },
...
});

And this is it. Hope it helps.

**Comment by philipobrien** [comment] 2015-08-20 08:29
@splendido Could you please give an example of what you mean by

> Solved by adding an onStop hook to clear the error every time you leave a protected route ;-)

**Comment by splendido** [comment] 2015-08-21 20:28
that was done into the UA code, so it should require no actions from your side.
Are you experiencing any problem?

**Comment by philipobrien** [comment] 2015-08-22 21:15
Apologies, the error was on my side. I was incorrectly configuring my routes. Works perfect now

**Comment by narigondelsiglo** [comment] 2017-07-01 14:31
Hi there, can anyone point me out what do I need to do when I have "/" route pointing to the dashboard (which is private), and the user arrives for the first time to the page. I'm always getting this message, except when loggin out.
Thanks, great work!
